#!/bin/bash

regex="^.*\.(ex|exs)$"

function printMessage() {
  echo -e "\033[90m$1\033[0m"
}

for file in $(git diff --diff-filter=d --name-only --cached); do
  if [[ $file =~ $regex ]]; then
    printMessage "Formatting $file"
    mix format "$file"
    git add "$file"
  fi
done
