name: Build
on: [ push, pull_request ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: erlef/setup-beam@v1.15.2
        with:
          otp-version: '25'
          elixir-version: '1.15'

      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.clean --unused
          mix deps.get
          mix deps.compile
        name: Compile Dependencies

      - run: |
          MIX_ENV=test mix coveralls.xml
        name: Unit Tests

      - run: |
          MIX_ENV=prod mix release
        name: Compile

      - run: |
          mix credo --sonarqube-base-folder ./ --sonarqube-file credo_sonarqube.json --mute-exit-status
          mix sobelow
          mix sobelow -f json --out sobelow.json
        name: Static Code Analysis

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}