name: Build
on: [push, pull_request]
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d171c3b028d844f2bf14e9fdec0c58114451e4bf
      - uses: erlef/setup-beam@10d50f70626dbb9c5174531ada017b8b4f14c215
        with:
          otp-version: '24'
          elixir-version: '1.9'

      - run: |
          mkdir ./cover
          mix local.hex --force
          mix local.rebar --force
          mix deps.clean --unused
          mix deps.get
          mix deps.compile
        name: Compile Dependencies

      - run: |
          MIX_ENV=test mix test --cover
        name: Run Tests

      - run: |
          MIX_ENV=performance mix escript.build
        name: Compile
