name: Build
on: [ push, pull_request ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: erlef/setup-beam@v1
        with:
          otp-version: '26'
          elixir-version: '1.16'

      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - run: |
          mix do local.hex --force, local.rebar --force
          mix do deps.clean --unused, deps.get, deps.compile
        name: Compile Dependencies

      - run: |
          docker run --name latency-simulator -d -p 8080:8080 bancolombia/latency-simulator:0.1.0
          mix coveralls.xml
          docker container rm -f latency-simulator
        name: Unit Tests

      - run: |
          mix release
        name: Compile

      - run: |
          mix credo --all --sonarqube-base-folder ./ --sonarqube-file credo_sonarqube.json --mute-exit-status
          mix sobelow --config
          mix sobelow -f json --out sobelow.json
        name: Static Code Analysis

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}