name: Deploy Image
on:
  release:
    types: [ published ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        if: "!github.event.release.prerelease"
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            bancolombia/distributed-performance-analyzer:latest
            bancolombia/distributed-performance-analyzer:${{ github.ref_name }}

      - name: Build and push - prerelease
        uses: docker/build-push-action@v4
        if: "github.event.release.prerelease"
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: bancolombia/distributed-performance-analyzer:${{ github.ref_name }}
